routes/web.php
<?php

use App\Models\User;
use App\Models\Project;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProjectController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [ProjectController::class, 'all'])->name('dashboard');
    Route::get('/profile/my-profile', [UserController::class, 'index']);
    Route::post('/profile/profile-update', [UserController::class, 'update'])->name('profile-update');
});

Route::middleware(['completed'])->group(function () {

    Route::get('/projects/my-projects', [ProjectController::class, 'index'])->name('my-projects');
    Route::get('/projects/create-project', [ProjectController::class, 'create']);
    Route::get('/projects/{id}/edit-project', [ProjectController::class, 'edit'])->name('edit-project');
    Route::get('/projects/{id}/delete', [ProjectController::class, 'destroy'])->name('delete-project');
    Route::post('/profile/create-project', [ProjectController::class, 'store'])->name('project-create');
    Route::put('/profile/{id}/edit-project', [ProjectController::class, 'update'])->name('project-edit');
    Route::get('/applications/my-applications', [ProjectController::class, 'myApplications']);
    Route::get('/applications/{id}/my-applications', [ProjectController::class, 'cancel'])->name('cancel');
    Route::get('/projects/{id}/applicants', [ProjectController::class, 'applicants'])->name('applicants');
    Route::put('/projects/{id}/applicants', [ProjectController::class, 'assemble'])->name('project-assemble');
    Route::get('/applicants/{id}/{name}-{surname}', [UserController::class, 'show'])->name('applicant-profile');
});


require __DIR__ . '/auth.php';

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Academy;
use App\Models\Project;
use function Ramsey\Uuid\v1;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\DB;
use function GuzzleHttp\Promise\all;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\ProjectRequest;
use Illuminate\Database\Eloquent\Builder;

class ProjectController extends Controller
{
    /**
     * Display user projects
     * 
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $projects = Project::where('projects.user_id', Auth::user()->id)
            ->orderBy('created_at', 'desc')
            ->get();

        $author = User::where('users.id', Auth::user()->id)
            ->join('academies', 'academies.id', 'users.academy_id')
            ->select('users.name as name', 'academies.id', 'users.academy_id', 'users.surname as surname', 'users.image as avatar', 'academies.profession as profession')
            ->get();


        return view('projects.my-projects', compact('projects', 'author'));
    }

    /**
     * display all academies as filter 
     *buttons on dashboard page
     */

    public function all()
    {
        $academies = Academy::all();

        return view('dashboard', compact('academies'));
    }

    /**
     * Create ne project page .
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $academies = Academy::all();

        return view('projects.create-project', compact('academies'));
    }

    /**
     * Sotre new project in db .
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectRequest $request)
    {
        $project = new Project();

        $project->title = $request->title;
        $project->description = $request->description;
        $project->user_id = Auth::user()->id;


        if ($project->save()) {
            $project->academies()->sync($request->academies);
            return redirect()->route('my-projects')->with('success', 'Project created! ');
        }
        return redirect()->back();
    }

    /**
     * edit project blade
     
     * list all data 
     * 
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = Project::find($id);
        $academies = Academy::all();

        $author = Auth::user()->id;

        if (($project->user_id != $author))
            abort(404);

        $project_academy = $project->academies()->pluck('academy_id')->toArray();

        return view('projects.edit-project', compact('project', 'academies', 'project_academy'));
    }

    /**
     * Update project .
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProjectRequest $request, $id)
    {
        $project = Project::find($id);

        $project->title = $request->title;
        $project->description = $request->description;

        if ($project->save()) {
            $project->academies()->sync($request->academies);
            return redirect()->route('my-projects')->with('success', 'Project edited! ');
        }
        return redirect()->back();
    }

    /**
     * Delete project .
     * only for authenticated users 
     * check if the user is author of the project
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project = Project::find($id);
        $author = Auth::user()->id;

        if (($project->user_id != $author))
            abort(404);

        Project::where('id', $id)->delete();

        $project->academies()->detach();
        $project->users()->detach();

        return redirect()->route('my-projects')->with('success', 'Project deleted! ');
    }

    /**
     * my applictions view page
     * list project data
     */

    public function myApplications()
    {
        $projects = Project::with('academies', 'author', 'users')
            ->withCount('users')
            ->whereRelation('users', 'user_id', '=', Auth::user()->id)
            ->orderBy('created_at', 'desc')
            ->get();
        return view('applications.my-applications', compact('projects'));
    }

    /**
     * cancel if application is denied 
     * check application status
     * check if user applied for the project
     */

    public function cancel($id)
    {

        $projects = Project::find($id);

        $project_check = Project::where('id', $id)
            ->whereHas('users', function ($query) {
                return $query->where('user_id', Auth::user()->id)
                    ->where('status', 'denied')
                    ->orWhere('status', 'request');
            })->value('id');

        if ($project_check == $id) {
            $projects->users()->wherePivot('user_id', Auth::user()->id)->detach();
            return redirect()->back();
        } else {
            abort(404);
        }
    }

    /**
     * list applicants data
     */

    public function applicants($id)
    {
        $details = Project::with('users')
            ->where('user_id', Auth::user()->id)
            ->whereHas('users', function ($query) use ($id) {
                return $query->where('project_id', $id);
            })->get();

        return view('projects.applicants', compact('details'));
    }

    /**
     * update project status
     * table (projects) 
     * column (is_assembled)
     */
    public function assemble($id)
    {
        $project = Project::find($id);

        $project->is_assembled = true;

        $denied = $project->users()->where('status', 'request')->pluck('id');

        if ($project->save()) {
            $project->users()->updateExistingPivot($denied, ['status' => 'denied']);
            return redirect()->back()->with('success', 'Team assembled! ');
        }

        return redirect()->back()->with('error', 'Error! ');
    }
}

resources/views/applications/my-applications.blade.php
@extends('layouts.master')

@include('layouts.navbar')

@section('title','My applications')

@section('css')
<link href="{{ asset('css/my-applications.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="container-fluid mt-5">
    <!-- project cards -->
    <div class="container mt-5">
        @foreach($projects as $project)
        <div class="col-lg-10 col-md-10 col-12 my-7 mx-auto">
            <div class="card mb-3 rounded mt-5 ">
                <div class="row g-0">
                    <div class="col-lg-4 col-md-4 col-12">
                        <div class="col-3 mx-auto">
                            <div class="card-image">
                                <img src="{{ asset('avatars/'. $project->author->image ) }}" class=" mx-auto project-image" alt="...">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="row">
                                <div class="col-12">
                                    <p class="mt-5  text-center semi-bold-bolder">{{$project->author->name}} {{$project->author->surname}}</p>
                                    <p class="mt-1 orange-custom classic-bold text-center ">I'm {{$project->author->academies->profession}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-7 col-12">
                        <div class="card-body ">
                            <h5 class="card-title classic-bold">{{$project->title}}</h5>
                            <p class="classic mt-3 showMore">{{$project->description}}</p>
                            <button class="applicants btn btn-outline-success p-lg-1 p-md-1 p-0">
                                <span class="font-applicants classic-bold">{{$project->users_count}}</span>
                                <p class="font-applicants classic">applicants</p>
                            </button>
                            @foreach($project->users as $status)
                            @if($status->pivot->user_id == Auth::user()->id)
                            @if(($status->pivot->status == 'request') || ($status->pivot->status == 'denied'))
                            <div class="edit-delete">
                                <a href="{{route('cancel',$project->id)}}" class="text-decoration-none">
                                    <img src="{{asset('custom_icons/2.png')}}" alt="" class="action-icon my-1">
                                    <p class="classic gray-custom ">Cancel</p>
                                </a>
                            </div>
                            @endif
                            @endif
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="card-footer bg-white">
                    <div class="row g-0 mb-1">
                        <div class="col-lg-10 col-md-12 col-12 ">
                            <div class="row mt-4 mx-auto">
                                <div class="col-lg-6 col-md-5 col-12 mt-lg-5 d-md-none d-block">
                                    @foreach($project->users as $status)
                                    @if($status->pivot->user_id == Auth::user()->id)
                                    @if($status->pivot->status == 'accepted')
                                    <p class="ms-2 green-custom semi-bold-bolder">Application Accepted
                                        <img class="action-icon" src="{{asset('custom_icons/5.png')}}" alt="">
                                    </p>
                                    @elseif($status->pivot->status == 'denied')
                                    <p class="ms-2 green-custom semi-bold-bolder">Application Denied
                                        <img class="action-icon" src="{{asset('custom_icons/6.png')}}" alt="">
                                    </p>
                                    @endif
                                    @endif
                                    @endforeach
                                </div>
                                <div class="col-6 text-center">
                                    <span class="gray-custom semi-bold-bolder text-center">I'm looking for</span>
                                </div>
                                <div class="col-lg-6 col-md-5 col-12 mt-lg-5 d-md-block d-none">
                                    @foreach($project->users as $status)
                                    @if($status->pivot->user_id == Auth::user()->id)
                                    @if($status->pivot->status == 'accepted')
                                    <p class="ms-2 green-custom semi-bold-bolder">Application Accepted
                                        <img class="action-icon" src="{{asset('custom_icons/5.png')}}" alt="">
                                    </p>
                                    @elseif($status->pivot->status == 'denied')
                                    <p class="ms-2 red-custom semi-bold-bolder">Application Denied
                                        <img class="action-icon" src="{{asset('custom_icons/6.png')}}" alt="">
                                    </p>
                                    @endif
                                    @endif
                                    @endforeach
                                </div>
                                <div class="col-lg-8 col-12 mt-2 ">
                                    @foreach($project->academies as $academy)
                                    <span class="text-wrap academies-circles text-white text-center semi-bold bg-green-custom p-lg-3 p-2">{{$academy->name}}</span>
                                    @endforeach

                                </div>
                            </div>
                        </div>
                        @if($project->is_assembled == true)
                        <div class="col-4">
                            <img src="{{asset('custom_icons/assembled.png')}}" class="assembled " alt="">
                        </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        @endforeach
    </div>
</div>
@endsection

@section('js')
<script src="{{ asset('js/readMoreLess.js') }}"></script>
@endsection